accounts/urls.py
# accounts/urls.py

from django.urls import path
from django.contrib.auth import views as auth_views
from .views import LoginView, RegisterView, LogoutView, ProfileView

app_name = 'accounts'

urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('register/', views.register, name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),

]

django_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django_app import views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

# Custom error handlers
handler404 = 'django_app.views.handler404'
handler500 = 'django_app.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('api/', include('polls.api_urls')),   
    path('accounts/', include('accounts.urls')),  # Include accounts URLs
    path('project/', include('project.urls')),  # Include accounts URLs
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

# Get list of Questions
# curl -X GET http://127.0.0.1:8000/api/questions/
# Create a new question
# curl -X POST http://127.0.0.1:8000/api/questions/ \
#      -H 'Content-Type: application/json' \
#      -d '{"question_text": "New Question?", "pub_date": "2024-10-16T12:00:00Z"}'

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('contact/', views.contact, name='contactform'),
    path('trigger-error/', views.trigger_error),
]

templates/base_generic.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}My Site{% endblock %}</title>
</head>
<body>
    {% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}!</p>
    <form method="post" action="{% url 'accounts:logout' %}">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
{% else %}
    <p><a href="{% url 'accounts:login' %}">Login</a> | <a href="{% url 'accounts:register' %}">Register</a></p>
{% endif %}

    {% block content %}
    <!-- Page-specific content will be rendered here -->
    {% endblock %}
</body>
</html>